---
title: "theory"
author: "Caleb Robbins"
date: "7/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(arrow)
library(neon4cast)
library(yardstick)
source(here("download_target.R"))
```


Ripping this code from Freya Olsson's tutorial: https://github.com/OlssonF/NEON-forecast-challenge-workshop/blob/main/Analyse_scores/Get_scores_tutorial.Rmd

```{r}
s3 <- arrow::s3_bucket(bucket = "neon4cast-scores/parquet/aquatics", endpoint_override= "data.ecoforecast.org")
s3_pheno <- arrow::s3_bucket(bucket = "neon4cast-scores/parquet/phenology", endpoint_override= "data.ecoforecast.org")
s3_terr <- arrow::s3_bucket(bucket = "neon4cast-scores/parquet/terrestrial_daily", endpoint_override= "data.ecoforecast.org")
s3_beetle <- arrow::s3_bucket(bucket = "neon4cast-scores/parquet/beetles", endpoint_override= "data.ecoforecast.org")

start_ref_date <- as_date('2023-04-13') # what period do you want the scores for?
end_ref_date <- as_date('2023-09-14')
get_refdates <- as.character(seq(start_ref_date, end_ref_date, by = 'day'))

get_sites <- readr::read_csv("https://raw.githubusercontent.com/eco4cast/neon4cast-targets/main/NEON_Field_Site_Metadata_20220412.csv", show_col_types = F) |> 
  #dplyr::filter(field_site_subtype == 'Wadeable Stream') |> # Subset to the stream sites
  select(field_site_id) |> #slice_head(n = 5)|>
  pull() # get in a vector

#get_variables <- c('temperature', 'oxygen', "gcc90", "nee", "beetles")

aq_scores <- open_dataset(s3) |>
  filter(reference_datetime %in% get_refdates,
         model_id == "tg_randfor",
         site_id %in% get_sites) |> 
  collect() |> 
  mutate(horizon = as.numeric(as_date(datetime) - as_date(reference_datetime)))

beetle_scores <- open_dataset(s3_beetle) |>
  filter(reference_datetime %in% get_refdates,
         model_id == "tg_randfor",
         site_id %in% get_sites,
         variable == "abundance") |> 
  collect() |> 
  mutate(horizon = as.numeric(as_date(datetime) - as_date(reference_datetime)))

terr_scores <- open_dataset(s3_terr) |>
  filter(reference_datetime %in% get_refdates,
         model_id == "tg_randfor",
         site_id %in% get_sites,
         variable == "nee") |> 
  collect() |> 
  mutate(horizon = as.numeric(as_date(datetime) - as_date(reference_datetime)))

pheno_scores <- open_dataset(s3_pheno) |>
  filter(reference_datetime %in% get_refdates,
         model_id == "tg_randfor",
         site_id %in% get_sites,
         variable == "rcc90") |> 
  collect() |> 
  mutate(horizon = as.numeric(as_date(datetime) - as_date(reference_datetime)))

scores_df <- bind_rows(aq_scores, beetle_scores,terr_scores)

```

```{r}

ggplot(data = blah, aes(x = horizon, y = mean-observation, color = variable))+
  geom_point()+
  facet_wrap(.~site_id)

# calculate R 2 for each forecast horizon and site

score_sums <- scores_df|>filter(horizon >=0)|>mutate(month = month(reference_datetime))|>group_by(variable,horizon, site_id, month)|>rsq(truth = observation, estimate = median)|>rename(r_squared = ".estimate")

ggplot(data = score_sums|>filter(variable == "oxygen"), aes(x = horizon, y = r_squared))+
  geom_point()+
  facet_wrap(.~month)+
  geom_smooth(method = "gam")

#suppose what we want to do is aggregate scores for each forecast horizon

```

View time series observations

```{r}

modobs <- read_csv(here("Generate_forecasts/tg_randfor/model_training_summaries.csv"))

ggplot(data = modobs, aes(x = target_variable, y = n_obs))+
  geom_point()+
  facet_wrap(.~theme, scales = "free")+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5))

```



```{r}
unique(scores_df$variable)
m1 <- gam(data = scores_df, 
          s(horizon, by = variable) +
          s(horizon, by = c(variable, season))+
          s(variable, bs = "re")+
          s(site_id, bs = "re")+
          s(site_id, horizon, bs = "re"))


```


View target observations
```{r}

aquatic_df <- download_target("aquatics")
beetle_df<- download_target("beetles")

beetle_t<- beetle_df|>
  pivot_wider(names_from = "variable", values_from = "observation")|>
  filter(abundance > 0)

ggplot(beetle_df|>mutate()|>filter(variable == "richness"), 
       aes(x = datetime, y = observation, color = site_id))+
  geom_line()

```